version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocognit
    - maligned
    - depguard
    - misspell
    - lll
    - unparam
    - nakedret
    - prealloc
    - gocritic
  disable:
    - gochecknoinits
